return { 
    crminibossscrapper = {
        name                = [[Scrapper]],
        description         = [[Protected Rush Boss Chickenid]],
        acceleration        = 1.08,
        activateWhenBuilt   = true,
        brakeRate           = 1.23,
        builder             = false,
        buildPic            = [[chicken_shield.png]],
        canGuard            = true,
        canMove             = true,
        canPatrol           = true,
        category            = [[LAND]],
        explodeAs           = [[NOWEAPON]],
        footprintX          = 4,
        footprintZ          = 4,
        health              = 1000,
        iconType            = [[walkershield]],
        idleAutoHeal        = 20,
        idleTime            = 300,
        leaveTracks         = true,
        maxSlope            = 37,
        maxWaterDepth       = 5000,
        metalCost           = 0,
        energyCost          = 0,
        buildTime           = 1200,
        movementClass       = [[BHOVER5]],
        noAutoFire          = false,
        noChaseCategory     = [[TERRAFORM FIXEDWING SATELLITE GUNSHIP SUB]],
        objectName          = [[chicken_shield.s3o]],
        power               = 350,
        reclaimable         = false,
        selfDestructAs      = [[NOWEAPON]],
        script = [[chicken_shield.cob]],
        sightDistance       = 512,
        sonarDistance       = 512,
        speed               = 54,
        trackOffset         = 7,
        trackStrength       = 9,
        trackStretch        = 1,
        trackType           = [[ChickenTrack]],
        trackWidth          = 34,
        turnRate            = 967,
        upright             = false,
        waterline           = 26,
        workerTime          = 0,

        sfxtypes            = {

            explosiongenerators = {
                [[custom:blood_spray]],
                [[custom:blood_explode]],
                [[custom:dirt]],
            },

        },
        customParams = {
            bosschickenidrole = [[rush]],
            powereggsondeath = 3,
            metaleggsondeath = 16,
            isscrapper = [[back]],
    unarmed       = true,
           -- shield_emit_height = 26,
          --  shield_emit_offset = 0,

            outline_x = 145,
            outline_y = 145,
            outline_yoff = 27.5,
        },
        weapons = {
            {
                def                = [[FAKE_WEAPON]],
                onlyTargetCategory = [[SWIM LAND SINK TURRET FLOAT SHIP HOVER]],
            },
        },


        weaponDefs = {
            FAKE_WEAPON = {
            name                    = [[Fake]],
            areaOfEffect            = 8,
            avoidFriendly           = false,
            collideFriendly         = false,
            craterBoost             = 0,
            craterMult              = 0,

            damage                  = {
                default = 0.01,
                planes  = 0.01,
            },

            explosionGenerator      = [[custom:NONE]],
            impactOnly              = true,
            impulseBoost            = 0,
            impulseFactor           = 0.4,
            interceptedByShieldType = 1,
            noSelfDamage            = true,
            range                   = 420,
            reloadtime              = 10,
            size                    = 0,
            soundHit                = [[]],
            soundStart              = [[]],
            targetborder            = 1,
            tolerance               = 5000,
            turret                  = true,
            waterWeapon             = false,
            weaponType              = [[Cannon]],
            weaponVelocity          = 500,
            },
        },
    },
    crminibossscrapper_front = {
        name                   = [[Scrapper Cover]],
        description            = [[Kill the back!]],
        acceleration           = 0.75,
        activateWhenBuilt      = true,
        brakeRate              = 4.5,
        buildPic               = [[shieldshield.png]],
        canGuard               = true,
        canMove                = true,
        canPatrol              = true,
        category               = [[LAND UNARMED]],
        corpse                 = [[DEAD]],
        explodeAs              = [[BIG_UNITEX]],
        footprintX             = 2,
        footprintZ             = 2,
        health                 = 700,
        iconType               = [[walkershield]],
        leaveTracks            = true,
        maxSlope               = 36,
        maxWaterDepth          = 5000,
        metalCost              = 600,
        movementClass          = [[AKBOT2]],
        moveState              = 0,
        objectName             = [[m-8.s3o]],
        onoffable              = true,
        script                 = [[shieldshield.lua]],
        selfDestructAs         = [[BIG_UNITEX]],
        sightDistance          = 300,
        speed                  = 61.5,
        trackOffset            = 0,
        trackStrength          = 8,
        trackStretch           = 1,
        trackType              = [[ChickenTrackPointy]],
        trackWidth             = 30,
        turnRate               = 2520,
        upright                = false,
        weapons                = {
            {
                def = [[COR_SHIELD_SMALL]],
            },
        },
        weaponDefs = {
            COR_SHIELD_SMALL = {
                name                    = [[Energy Shield]],
                damage                  = {
                    default = 10,
                },
                exteriorShield          = true,
                shieldAlpha             = 0.2,
                shieldBadColor          = [[1 0.1 0.1 1]],
                shieldGoodColor         = [[0.1 0.1 1 1]],
                shieldInterceptType     = 3,
                shieldPower             = 1200,
                shieldPowerRegen        = 50,
                shieldPowerRegenEnergy  = 12,
                shieldRadius            = 50,
                shieldRepulser          = false,
                smartShield             = true,
                visibleShield           = false,
                visibleShieldRepulse    = false,
                --texture1                = [[shield3mist]],
                --visibleShield           = true,
                --visibleShieldHitFrames  = 4,
                --visibleShieldRepulse    = true,
                weaponType              = [[Shield]],
            },
        },
        featureDefs = {
        },
        customParams = {
            priority_misc = 1, -- Medium
            unarmed       = true,
            aimposoffset   = [[0 5 0]],
            
            isscrapper = [[front]],
            outline_x = 80,
            outline_y = 80,
            outline_yoff = 12.5,
        },
    },
}
