return { 
	eggbasket = {
		name                          = [[Egg Basket]],
		description                   = [[Bring me eggs. Now.]],
		activateWhenBuilt             = true,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 5,
		buildingGroundDecalSizeY      = 5,
		buildingGroundDecalType       = [[energypylon_aoplane.dds]],
		buildPic                      = [[energypylon.png]],
		category                      = [[SINK UNARMED]],
		collisionVolumeOffsets        = [[0 0 0]],
		collisionVolumeScales         = [[42 42 42]],
		collisionVolumeType           = [[cylY]],
		selectionVolumeOffsets        = [[0 0 0]],
		selectionVolumeScales         = [[46 38 46]],
		selectionVolumeType           = [[cylY]],
		corpse                        = [[DEAD]],

		customParams                  = {
			iseggbasket = 1,
			aimposoffset   = [[0 0 0]],
			midposoffset   = [[0 -6 0]],
			modelradius    = [[24]],
			removewait     = 1,
			removestop     = 1,
			default_spacing = 41, -- Diagonal connection.
			selectionscalemult = 1.15,
			stats_show_death_explosion = 1,
		},

		explodeAs                     = [[ESTOR_BUILDINGEX]],
		footprintX                    = 3,
		footprintZ                    = 3,
		health                        = 1000,
		iconType                      = [[pylon]],
		levelGround                   = false,
		maxSlope                      = 18,
		metalCost                     = 200,
		noAutoFire                    = false,
		objectName                    = [[armestor.s3o]],
		script                        = "energypylon.lua",
		selfDestructAs                = [[ESTOR_BUILDINGEX]],
		sightDistance                 = 273,
		useBuildingGroundDecal        = true,
		yardMap                       = [[ooo ooo ooo]],

		featureDefs                   = {

			DEAD  = {
				blocking         = true,
				collisionVolumeScales = [[42 42 42]],
				collisionVolumeType   = [[cylY]],
				featureDead      = [[HEAP]],
				footprintX       = 3,
				footprintZ       = 3,
				object           = [[ARMESTOR_DEAD.s3o]],
			},

			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = [[debris4x4b.s3o]],
			},
		},
	},
	eggbasketinactive = {
		name                          = [[Egg Basket (Inactive)]],
		description                   = [[Too soon, Eggsecutis!]],
		activateWhenBuilt             = true,
		builder                       = false,
		buildingGroundDecalDecaySpeed = 30,
		buildingGroundDecalSizeX      = 5,
		buildingGroundDecalSizeY      = 5,
		buildingGroundDecalType       = [[staticstorage_aoplane.dds]],
		buildPic                      = [[staticstorage.png]],
		category                      = [[SINK UNARMED]],
		collisionVolumeOffsets        = [[0 0 0]],
		collisionVolumeScales         = [[60 60 60]],
		collisionVolumeType           = [[ellipsoid]],
		corpse                        = [[DEAD]],
		explodeAs                     = [[SMALL_BUILDINGEX]],
		footprintX                    = 3,
		footprintZ                    = 3,
		health                        = 700,
		iconType                      = [[storage]],
		maxSlope                      = 18,
		metalCost                     = 100,
		objectName                    = [[pylon.s3o]],
		script                        = "staticstorage.lua",
		selfDestructAs                = [[SMALL_BUILDINGEX]],
		sightDistance                 = 273,
		useBuildingGroundDecal        = true,
		yardMap                       = [[ooo ooo ooo]],

		customParams                  = {
			iseggbasket			= 1,
			modelradius			= [[30]],
			removewait			= 1,
			removestop			= 1,
			default_spacing		= 0,
			selectionscalemult	= 1.15,
		},

		featureDefs                   = {

			DEAD  = {
				blocking         = true,
				featureDead      = [[HEAP]],
				footprintX       = 3,
				footprintZ       = 3,
				object           = [[storage_d.dae]],
			},

			HEAP  = {
				blocking         = false,
				footprintX       = 3,
				footprintZ       = 3,
				object           = [[debris4x4c.s3o]],
			},

		},
	},
}
